### PR TITLE
DRAFT: static + const.

### PR DESCRIPTION
**Pull request by KuehnhammerTobias**
# More static and const, actually more const than static.
This pull request is marked as draft.
Like you did it before for Q3e, and many other projects also do it nowadays, this PR will add 'const' to constants/literals.

Most of the changes are already made in other projects, like Spearmint, WorldOfPadman, etc. I'm pretty sure there are more parts of the code that could be constants. Anyways, I only declared those as constant that gives me no errors, crashes, or warnings, and everything works like before (at least for me). Though, you really should check this out before using this PR, or parts of it.

Consider this PR as a template, hence it's marked as draft. Please let me know if I should unmark it.
If not, please close this pull request.

## ***What is changing:***
  + Make possible constants 'const'.
## ***Notes:***
  + Most of the changes are taken from World of Padman (e.g: https://github.com/PadWorld-Entertainment/worldofpadman/commit/c0894904f7dead773c4d053e6efbd9779323044c) and more.

### CODE REVIEW

**Comment by ensiform** [comment]
Surprised there's no AI or automated tool that can detect cases where you can use both in a codebase in C still. C++ has const correctness guidelines now.

**Comment by KuehnhammerTobias** [comment]
Yes, AI would be helpful, unfortunately I don't know of any.
Fortunately, at least the compiler complains.

**Comment by ensiform** [comment]
vec3_origin as const is a mistake for codebases which have gamecode linked against this. Too much noise to fix because of places that don't accept const vec3_t

**Comment by KuehnhammerTobias** [comment]
> vec3_origin as const is a mistake for codebases which have gamecode linked against this. Too much noise to fix because of places that don't accept const vec3_t

Can you please point out what codebases you mean? I want to have a look at them.
Currently I have fully 'const' made game codebases based on baseq3a, mint-arena, ioq3 game code, and WoP (where nearly everything was turned to 'const' already). I don't know of any game code that don't accept vec3_origin as const.
I'll look at the game code you are referring to.

**Comment by ensiform** [comment]
Have you ever checked clang and not just gcc ?

W:ET

```
/home/user/Projects/ete/src/game/g_weapon.c:2598:34: warning: passing 'const vec3_t' (aka 'vec_t const[3]') to parameter of type 'vec_t *' (aka 'float *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        gentity_t* tent = G_TempEntity( vec3_origin, event );
                                        ^~~~~~~~~~~
/home/user/Projects/ete/src/game/g_local.h:1176:33: note: passing argument to parameter 'origin' here
gentity_t *G_TempEntity( vec3_t origin, int event );
```

I'm not going to change every instance of vec3_t input to const in the entire ET codebase just for this.

**Comment by KuehnhammerTobias** [comment]
Ah, well, actually this PR is about Q3 (and mods), not Enemy Territory. As far as ET is concerned you are right of course. If porting or re-using Q3e for other games (> Q3) more adjustments would be needed, [as you pointed out recently for yourself](https://github.com/ec-/Quake3e/issues/164).
Anyways, if you want to revert those changes, it is okay to me, we can also make such a 'const' PR for your engine if you want.
I can also make a PR for baseq3a that makes use of 'const' for vec3_origin. It works well, even for old, compiled, closed source mods, it works also for Spearmint/mint-arena that supports most of RtCW and ET stuff.
Anyways, like I said, this PR was marked as 'Draft', you can revert the changes if you want.

**Comment by ensiform** [comment]
Correct it is for Q3, but as I pull as much as possible into ET for ETe, I like to try to make it all work unless it is a feature that is specifically different or removed such as QVM.

**Pull request merged**
