### PR TITLE
app will search for pk3 inside and next to the app bundle

### PR DESCRIPTION
**Pull request by Bishop-333**
I updated the icon as well because of a demand of a another mac user and its more original than the previous who was the same as ioquake3

### CODE REVIEW

**Comment by Bishop-333** [comment]
I'll try to correct the build on windows machine and explain more precisely what ive done

**Comment by Bishop-333** [comment]
So instead of making the apple executable looking into the hidden directory named .q3a it will look at 3 differents locations : Library/Application Support/Quake3/baseq3 or baseq3 next to the executable or baseq3 inside the .app.
Apple users are not really used to hidden folders so no more .q3a created for mac users.
I look at the makefile and it should not impact any windows machine since unix things are not compiled if im right.
For the unix machine it will not change anything too normally.
It's just backporting the thing who work for me from ioquake3.

**Review by ensiform — APPROVED** [review]

**Comment by Bishop-333** [comment]
@ec- I think it's ready to merge

**Comment by ec-** [comment]
Please group all apple-related code in smaller file count (`unix_main.c` only for example) and do not declare apple-specific function prototypes in `qcommon.h` if it is never used on other platforms

**Comment by Bishop-333** [comment]
> Please group all apple-related code in smaller file count (`unix_main.c` only for example) and do not declare apple-specific function prototypes in `qcommon.h` if it is never used on other platforms

I'll try to do that but isnt it necessary to have functions defined in qcommon.h to have files.c and unix_main connected with the same functions ? Maybe I'm wrong

**Comment by Bishop-333** [comment]
> > I'll try to do that but isnt it necessary to have functions defined in qcommon.h to have files.c and unix_main connected with the same functions ? Maybe I'm wrong
> 
> How does `Sys_SetDefaultBasePath()` and `Sys_Dirname()` related to that?

You right for theses two they are useless, i'll remove them in qcommon.h.
but you talked about the apple specific function like Sys_DefaultAppPath who is expressed only for apple machine can I let it in qcommon.h ?

**Pull request merged**
