### PR TITLE
s_volume becomes mastervolume for s_musicvolume

### PR DESCRIPTION
**Pull request by thefakeryker**

### CODE REVIEW

**Comment by KuehnhammerTobias** [comment]
Just a NOTE: it seems different people expect different behaviour: https://github.com/ioquake/ioq3/issues/502
Personally I can't say what the 'correct' behaviour is.

**Comment by ec-** [comment]
Well, it seems to broke config compatibility a bit but current behavior (-independend sfx and music control) is more convenient because you can emulate any vq3 combinations with it - while opposite (like sfx_vol=0 + musiv_vol=1 i.e. leave only music) is not possible

**Comment by thefakeryker** [comment]
image
I feel that having s_volume as the master volume is what it was originally supposed to be, but anyways, I added 's_mastervolume'.

**Comment by KuehnhammerTobias** [comment]
I think if you call current s_volume something different (somnething like s_effectsVolume) and s_volume will act as your 'mastervolume' than even existing cfgs will not break (something ec- tries to avoid if I'm correct).
This would be more user friendly.

**Comment by Kr3m** [comment]
>I feel that having s_volume as the master volume is what it was originally supposed to be, but anyways, I added 's_mastervolume'.

If Carmack intended s_volume to be the master volume, he wouldn't have coded it the way he did.  s_volume has ALWAYS been to control game volume where s_musicVolume was an option to separate it from the game volume for people who wanted the music volume disabled.  To change s_volume now, 25 years later, would be a terrible idea.

That aside, I'd have to look at your code changes to figure out whether s_masterVolume is even a good idea.  Would it change s_volume and s_musicVolume proportionately based on their current settings or is the intention to have them both statically set to one volume?  If the latter case, why?  If the former case, at least that makes some sense...

**Pull request closed without merging**
