### PR TITLE
Auto complete game server commands in console (Tremulous style).

### PR DESCRIPTION
**Pull request by KuehnhammerTobias**
This will auto-complete game server commands like 'entitylist', 'listip', 'rotate', etc.
Many games use this nowadays, for example Tremulous (which this PR is based upon): https://github.com/darklegion/tremulous/commit/4bede371a0f04d5edf3bd28f503ccf11cc9c6f47#diff-c7a9cbceb501eb5d6544b8bbcd16fde0 or Spearmint: https://github.com/zturtleman/ioq3ztm/commit/be4170e1cf7ba36494597c99488da0f2a3dbef7a#diff-71be0bce1bd44f613eb62959ede7fa2a.
This feature is very handy, decide for yourself if you like it or not. Since engine and mod code are in two seperate repositories, I also made a PR for the game code.
Feel free to do whatever you want with this PR.

### CODE REVIEW

**Comment by ec-** [comment]
This is practically useless without full mod-side support (which should be implemented though trag_getValue extension to keep vq3 API compatibility), and Tremulous is a standalone game, we don't have so much freedom in q3a

**Comment by KuehnhammerTobias** [comment]
Can you modify this to keep vq3 API compatibility, with this 'magical' not-API-breaking-feature you talked about? I don't understand it, or is this not possible at all?

**Comment by ensiform** [comment]
The binary search isn't really useful.

**Comment by KuehnhammerTobias** [comment]
Well, if it isn't useful than it isn't worth the trouble, closing now.

**Comment by ensiform** [comment]
The rest of it is fine, it's just better to have a generic linear search. As, binary search requires sorting and has no real speed benefits for these small arrays.

**Pull request closed without merging**
