### PR TITLE
CVARS: add more cvar descriptions.

### PR DESCRIPTION
**Pull request by KuehnhammerTobias**
# Complete almost all CVAR descriptions.
This pull request tries to describe as much CVARS as possible, as explained here: https://github.com/ec-/Quake3e/issues/188
As always feel free whatever you want to do with this pull request. Use it, change it, or skip it!
## ***What is changing:***
  + Add descriptions for most of the Q3e engine CVARS (by using the already existing Cvar_SetDescription functionality).
  + Establishing a constant cvar line order in a few places (1. Cvar, 2. RangeCheck, 3. Description).
  + Minor cosmetic fixes (constant cvar naming scheme - avoid mixing CamelCase).
## ***Notes:***
  + I used CVAR descriptions I found at the internet. I don't understand all of them, and I don't know if the cvars really do what the description says. On the contrary, I'm pretty sure some CVARS had never worked before. No malfunctioning CVARS have been fixed.
  + Of course, there are also many CVARS that are not described and are not listed here. Either because they elude the current Cvar SetDescription functionality (not registered), or because they cannot or do not have to be described for whatever reason.
  + With the exception of some spelling fixes, I took the descriptions 1:1 from some strange and not so strange Quake 3 related sites. Good descriptions I found here: https://www.excessiveplus.net/forums/thread/commandcvar-list-of-e-quake?page=1
  Thanks for that! Thanks also to themuffinator!
#

### CODE REVIEW

**Review by ec- — APPROVED** [review]

**Comment by ec-** [comment]
This is huge, thank you!

**Comment by ensiform** [comment]
Some of the cvars note what the default is in the description but this is redundant as the previous line will show current value and "default is <x>" btw

**Comment by KuehnhammerTobias** [comment]
@ec You are 100%-superman-hero! Thanks a lot to tweak the descriptions!

**Comment by ensiform** [comment]
```c
Cvar_SetDescription( sv_gametype, "Set the gametype to mod using sv_gametype." );
```

This also stuck out as odd? There is no such "sv_gametype" this is a code variable name only.

**Comment by KuehnhammerTobias** [comment]
Hi @ensiform!
I appreciate your technical skills and comments, could you imagine doing more explanations here: https://github.com/ec-/Quake3e/issues/188
This PR is already applied and closed, but the according issue is still open for suggestions improvements. I'm pretty sure you experts wil find much more strange things...

**Pull request merged**
