### PR TITLE
CMake options fixed.

### PR DESCRIPTION
**Pull request by Alex20129**
Couple of fixes to make it compile properly. `Tested under Ubuntu 20.04 only`

### CODE REVIEW

**Comment by ensiform** [comment]
${CMAKE_DL_LIBS} should be used in place of `dl`. But I'm not sure what cmake version level is necessary to put for the minimum.

**Comment by Alex20129** [comment]
okay

**Comment by ensiform** [comment]
You do know you don't have to keep making new pull requests for every single fix. Just keep pushing to the same branch.

**Comment by Alex20129** [comment]
> You do know you don't have to keep making new pull requests for every single fix. Just keep pushing to the same branch.

Ok, got it.

**Pull request closed without merging**
